name: Run Unit Tests

on:
  push:
    branches:
      - main
      - task-2  # Recommended: Trigger on your current working branch too
      - task-3  # Recommended: Trigger on your current working branch too 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install TA-Lib Binary
        run: |
          sudo apt-get update
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html
